
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm audit || true
  displayName: 'check the module for vulnarabilities'
  
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- script: |
    docker build -t jayapriya054/demo-frontend:$(Build.BuildId) . -f Dockerfile
  displayName: 'build container image'

- script: |
    docker run -d jayapriya054/demo-frontend:latest
  displayName: 'Run the application'

- script: |
    docker ps
  displayName: 'Verify container is running'

- task: Docker@2
  inputs:
    containerRegistry: dockerhub
    repository: jayapriya054/demo-frontend
    command: 'push'
    Dockerfile: 'latest'
  displayName: 'Docker connection'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Kubernetes'
    namespace: default
    command: 'apply'
    configuration: 'k8s/simple'
    arguments: -f .

- script: |
    sleep 60
  displayName: 'Wait for load balancer to come up'

- script: |
    set -i "s/jayapriya054/demo-frontend:latest/jayapriya054/demo-frontend:$(Build.BuildId)/g"/k8s/simple/frontend-deployment.yaml
    git add k8s/simple/frontend-deployment.yaml
    git commit -m "Uploaded the deployment manifest with image name $(Build.BuildId)"
    git push origin main

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'Kubernetes'
    namespace: default
    command: 'apply'
    configuration: 'k8s/simple'
    arguments: service coit-frontend-lb

# - task: Kubernetes@1
#  inputs:
#   connectionType: 'Kubernetes Service Connection'
#   kubernetesServiceEndpoint: 'Kubernetes'
#   namespace: default
#   command: 'set'
#   configuration: 'k8s/simple'
#   arguments: image deployment coit-frontend jayapriya054/demo-frontend=jayapriya054/demo-frontend:$(Build.BuildId)


